openai:
  api_key: "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"
  engine: "text-davinci-002"

params:
  temperature: 0.7
  max_tokens: 150
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
